name: Handle issues
on: issues
jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "${{ toJSON(github.event) }}"



####### factory feed CICD pending 

# git checkout main
# git pull

# npm install 
# export PORT=8080
# export COPILOT_ENVIRONMENT_NAME='prod' 
# db-migrate up --config common/database.json --env prod
# node app