name: Matrix demo
on: push
jobs:
    build:
        continue-on-error: true
        strategy:
            matrix:
                node-verson: [ 12, 14, 16]
                operating-system: [ ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.operating-system }}
        steps:
            - name: get code
              uses: actions/checkout@v4
            - name: install node
              uses: actions/setup-node@v4
              with: 
                node-version: ${{ matrix.node-verson }}
            - name: Install dependies
              run: npm ci
            - name: build 
              run: npm run build


############# In this we are using matrix 

#### exlpation:

### strategy $ matrix are the reserved keyword
### when we want to build or running our application test on different platfrom like windows , linus we cannot repeat the same steps
## again and again so at that time we use metri method 
### in this application we are using the both ubuntu , windows to test and i also specified the node version so it will be tested 
## on all the version  
### so at the end of the test we will get to know that which one is the compatible for the appliction depoyment


#### we aslo added the continue on error in this example because when it will run the matrix condition if on step is get failed it
### wont get execut the remaining condition so thats why we use the continue on error so it will check and execute all the condition