name: Reusable WF
on:
    workflow_call:
        inputs:
          artifact-name:
            description: The name of the deployment artifact
            required: false
            default: dist
            type: string

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v4
            - name: download artifact
              uses: actions/download-artifact@v4
              with: 
                name: ${{ inputs.artifact-name }}
            - name: Deploying successfully
              run: echo "Deployed successfully"




#### this is reusable workflow so we can use this workflow in other WF 
#### workflow_call is a function is allow us to use this workflow 


### this input is a reserver key word
### artifact-name is user defined
## remaining words are the reserved works where it will used to give inputs where it is called
