name: Testing CICD      
on:
  pull_request:  #### this indicates on with the workflow should trigger in this i mentione on pull request
    types:     ## types indicates types of reqquest opened in the repo
        - opened
        - reopened
        - closed
    branches:      ##### thisindicates we can spefice when the changes is made in branches it should only trigger mentioned branch
        - main    
  workflow_dispatch: ##### this indicates where we can run the workflow manully via console
  push:             #### this indicates on with the workflow should trigger if they push code to mentione branch 
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'CD.yaml'           ###### keyworkds: name, on, pull_request, push, types, branches, jobs, runs-on, steps, uses,run
jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  install:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
  test:
    needs: install
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test code
        run: npm run test
  artifacts:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy code
        run: echo "Deploying..." 
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
            name: dist-files
            path: |
              dist
              package.json
  download_artifact:
    needs: artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
  deploy:
    needs: [ test,download_artifact]  
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy code
        run: echo "Deploying..." 
  
        

